-- CONSULTA
ALTER TABLE consulta
ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;

UPDATE consulta SET ativo = TRUE;

-- MEDICO
ALTER TABLE medico
ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;

UPDATE medico SET ativo = TRUE;

-- PACIENTE
ALTER TABLE paciente
ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;

UPDATE paciente SET ativo = TRUE;
